// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shiluns.netty.rpc.grpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiluns.netty.rpc.grpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string realname = 1;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>optional string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
