// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shiluns.netty.rpc.grpc;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiluns.netty.rpc.grpc.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string response_info = 1;</code>
   */
  java.lang.String getResponseInfo();
  /**
   * <code>optional string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
