// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shiluns.netty.rpc.grpc;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiluns.netty.rpc.grpc.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 age = 1;</code>
   */
  int getAge();
}
