// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shiluns.netty.rpc.grpc;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shiluns.netty.rpc.grpc.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shiluns.netty.rpc.grpc.StudentResponse student = 1;</code>
   */
  java.util.List<com.shiluns.netty.rpc.grpc.StudentResponse> 
      getStudentList();
  /**
   * <code>repeated .com.shiluns.netty.rpc.grpc.StudentResponse student = 1;</code>
   */
  com.shiluns.netty.rpc.grpc.StudentResponse getStudent(int index);
  /**
   * <code>repeated .com.shiluns.netty.rpc.grpc.StudentResponse student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .com.shiluns.netty.rpc.grpc.StudentResponse student = 1;</code>
   */
  java.util.List<? extends com.shiluns.netty.rpc.grpc.StudentResponseOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .com.shiluns.netty.rpc.grpc.StudentResponse student = 1;</code>
   */
  com.shiluns.netty.rpc.grpc.StudentResponseOrBuilder getStudentOrBuilder(
      int index);
}
