// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shiluns.netty.rpc.grpc;

public final class StudentInfo {
  private StudentInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiluns_netty_rpc_grpc_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiluns_netty_rpc_grpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiluns_netty_rpc_grpc_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiluns_netty_rpc_grpc_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiluns_netty_rpc_grpc_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiluns_netty_rpc_grpc_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiluns_netty_rpc_grpc_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiluns_netty_rpc_grpc_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiluns_netty_rpc_grpc_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiluns_netty_rpc_grpc_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiluns_netty_rpc_grpc_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiluns_netty_rpc_grpc_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shiluns_netty_rpc_grpc_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shiluns_netty_rpc_grpc_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\032com.shiluns.netty.rpc.g" +
      "rpc\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMy" +
      "Response\022\020\n\010realname\030\001 \001(\t\":\n\017StudentRes" +
      "ponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city" +
      "\030\003 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 \001(\005\"S\n" +
      "\023StudentResponseList\022<\n\007student\030\001 \003(\0132+." +
      "com.shiluns.netty.rpc.grpc.StudentRespon" +
      "se\"%\n\rStreamRequest\022\024\n\014request_info\030\001 \001(" +
      "\t\"\'\n\016StreamResponse\022\025\n\rresponse_info\030\001 \001" +
      "(\t2\250\003\n\016StudentService\022^\n\rGetByUsername\022%",
      ".com.shiluns.netty.rpc.grpc.MyRequest\032&." +
      "com.shiluns.netty.rpc.grpc.MyResponse\022e\n" +
      "\010GetByAge\022*.com.shiluns.netty.rpc.grpc.S" +
      "tudentRequest\032+.com.shiluns.netty.rpc.gr" +
      "pc.StudentResponse0\001\022j\n\tGetByAges\022*.com." +
      "shiluns.netty.rpc.grpc.StudentRequest\032/." +
      "com.shiluns.netty.rpc.grpc.StudentRespon" +
      "seList(\001\022c\n\006BiTalk\022).com.shiluns.netty.r" +
      "pc.grpc.StreamRequest\032*.com.shiluns.nett" +
      "y.rpc.grpc.StreamResponse(\0010\001B+\n\032com.shi",
      "luns.netty.rpc.grpcB\013StudentInfoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_shiluns_netty_rpc_grpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_shiluns_netty_rpc_grpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiluns_netty_rpc_grpc_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_shiluns_netty_rpc_grpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_shiluns_netty_rpc_grpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiluns_netty_rpc_grpc_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_shiluns_netty_rpc_grpc_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_shiluns_netty_rpc_grpc_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiluns_netty_rpc_grpc_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_shiluns_netty_rpc_grpc_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_shiluns_netty_rpc_grpc_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiluns_netty_rpc_grpc_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_shiluns_netty_rpc_grpc_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_shiluns_netty_rpc_grpc_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiluns_netty_rpc_grpc_StudentResponseList_descriptor,
        new java.lang.String[] { "Student", });
    internal_static_com_shiluns_netty_rpc_grpc_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_shiluns_netty_rpc_grpc_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiluns_netty_rpc_grpc_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_shiluns_netty_rpc_grpc_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_shiluns_netty_rpc_grpc_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shiluns_netty_rpc_grpc_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
